const CANVAS_WIDTH = 500
const CANVAS_HEIGHT = 500
const GRID_LINE_WIDTH = 1
const GRID_CELL_WIDTH = 25
const GRID_WIDTH_COUNT = CANVAS_WIDTH / GRID_CELL_WIDTH
const GRID_HEIGHT_COUNT = CANVAS_HEIGHT / GRID_CELL_WIDTH

const BACKGROUND_COLOR = ''
const GRID_LINE_COLOR = '#332522'
const GRID_BORDER_COLOR = '#332522'
const COLLISION_COLOR = '#19634B'
const START_COLOR = '#00A36C'
const PATH_COLOR = 'cyan'
const END_COLOR = '#A32000'

const CELL_STATES = {
 EMPTY: 0,
 COLLISION: 1,
 START: 2,
 END: 3,
 PATH: 4
}